services:
  - type: web
    name: prodigy-mun-backend
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm run start:server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
    healthCheckPath: /api/registrations/stats